AWSTemplateFormatVersion: 2010-09-09
Description: >-
  emails-queue-service

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  AccountId:
    Type: String
    Description: AWS account ID
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      bucket: emails-service-storage
    test:
      bucket: emails-service-storage-test

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 60

  SQSPayloadProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Description: Processes queued messages to send emails.
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: handlers/sqs-payload-processor.sqsPayloadProcessorHandler
      CodeUri: './dist'
      Environment:
        Variables:
          EMAIL_BUCKET: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
          EMAIL_REGION: us-east-1
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            BatchSize: 7
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 60
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to S3 bucket
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
        # Grant access to SES identity
        - SESCrudPolicy:
            IdentityName: bowland.link
        # Grant access to SQS queue
        - SQSPollerPolicy:
            QueueName: !GetAtt SimpleQueue.QueueName

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [SQSPayloadProcessor]
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSPayloadProcessor}
      RetentionInDays: 30
