AWSTemplateFormatVersion: 2010-09-09
Description: >-
  emails-queue-service

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - test
    Description: Environment for deploy

Mappings:
  EnvironmentMap:
    prod:
      bucket: emails-service-storage
      domain: dbowland.com
      errorTopic: arn:aws:sns:us-east-1:494887012091:error-topic
      project: emails-queue-service
    test:
      bucket: emails-service-storage-test
      domain: bowland.link
      errorTopic: arn:aws:sns:us-east-1:494887012091:error-topic-test
      project: emails-queue-service-test

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      KmsMasterKeyId: alias/aws/sqs
      MessageRetentionPeriod: 1209600 # 14 days
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60

  SQSPayloadProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - x86_64
      CodeUri: './dist'
      Description: Processes queued messages to send emails.
      Environment:
        Variables:
          DOMAIN: !FindInMap [EnvironmentMap, !Ref Environment, domain]
          EMAIL_BUCKET: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
          EMAIL_REGION: us-east-1
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            BatchSize: 7
            Queue: !GetAtt SimpleQueue.Arn
      Handler: handlers/sqs-payload-processor.sqsPayloadProcessorHandler
      MemorySize: 128
      Policies:
        # Give Lambda basic execution Permission
        - AWSLambdaBasicExecutionRole
        # Grant access to S3 bucket
        - S3CrudPolicy:
            BucketName: !FindInMap [EnvironmentMap, !Ref Environment, bucket]
        # Grant access to SES identity
        - SESCrudPolicy:
            IdentityName: !FindInMap [EnvironmentMap, !Ref Environment, domain]
        # Grant access to SQS queue
        - SQSPollerPolicy:
            QueueName: !GetAtt SimpleQueue.QueueName
      Runtime: nodejs14.x
      Timeout: 60

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: [SQSPayloadProcessor]
    Properties:
      LogGroupName: !Sub /aws/lambda/${SQSPayloadProcessor}
      RetentionInDays: 30

  ErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    DependsOn: [LambdaLogGroup]
    Properties:
      FilterPattern: '[timestamp, uuid, level="ERROR", message]'
      LogGroupName: !Sub /aws/lambda/${SQSPayloadProcessor}
      MetricTransformations:
        - MetricValue: '1'
          MetricNamespace: !Sub
            - 'dbowland/${Project}'
            - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
          MetricName: ErrorCount

  ErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !FindInMap [EnvironmentMap, !Ref Environment, errorTopic]
      AlarmDescription: Error alarm for emails-queue-service
      AlarmName: !FindInMap [EnvironmentMap, !Ref Environment, project]
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      MetricName: ErrorCount
      Namespace: !Sub
        - 'dbowland/${Project}'
        - Project: !FindInMap [EnvironmentMap, !Ref Environment, project]
      Period: 60
      Statistic: Maximum
      Threshold: 1
      TreatMissingData: notBreaching
