version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::494887012091:user/aws-sam-cli-managed-prod-pipeline-res-PipelineUser-D2F832ET986E"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::494887012091:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-MJL5WDWSUADJ"
cloudformation_execution_role = "arn:aws:iam::494887012091:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-175EQOZKAQ42Z"
artifacts_bucket = "emails-lambda-source"
image_repository = ""
region = "us-east-1"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::494887012091:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-DRD9O21EQL33"
cloudformation_execution_role = "arn:aws:iam::494887012091:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1VAGXTZ6YPX38"
artifacts_bucket = "emails-lambda-source"
image_repository = ""
region = "us-east-1"
